<a href="https://colab.research.google.com/github/rithika270305/Numpy-Learnings/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

**1.Creating numpy arrays**

In [2]:
a=np.array([1,2,3])
a

array([1, 2, 3])

In [3]:
print(type(a))

<class 'numpy.ndarray'>


In [4]:
b=np.array([[1,2,3],[4,5,6]])
b

array([[1, 2, 3],
       [4, 5, 6]])

In [5]:
type(b)

numpy.ndarray

In [6]:
c=np.array([1,2,3],dtype=float)
c  # dtype=bool/complex.

array([1., 2., 3.])

In [7]:
np.arange(1,12) #1 included 12 excluded

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [8]:
np.arange(1,100,25)

array([ 1, 26, 51, 76])

In [9]:
x=np.arange(1,21).reshape(5,4) #number of elements= row*column
x

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20]])

In [10]:
np.ones((3,4)) #application in neural networks

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [11]:
np.zeros((4,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [12]:
np.random.random((3,5))

array([[0.3903896 , 0.85361976, 0.77166305, 0.93836279, 0.90101441],
       [0.17625468, 0.12427383, 0.76481677, 0.67855259, 0.48715941],
       [0.32577319, 0.71041498, 0.75328066, 0.96170241, 0.90698328]])

In [13]:
np.linspace(-10,10,10) #from -10 to 10 generates 10 points each of equal distance

array([-10.        ,  -7.77777778,  -5.55555556,  -3.33333333,
        -1.11111111,   1.11111111,   3.33333333,   5.55555556,
         7.77777778,  10.        ])

In [14]:
np.identity(5) #square matrix where diagnoal=1

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

**2.Array attributes**

In [15]:
a.ndim #number of dimensions

1

In [16]:
b.ndim

2

In [17]:
c.shape

(3,)

In [18]:
b.shape

(2, 3)

In [19]:
x.shape

(5, 4)

In [20]:
x.size

20

In [21]:
x.itemsize #int32 = 4bytes, int64= 8bytes

8

In [22]:
a.dtype

dtype('int64')

In [23]:
a.astype(np.int32) #to save memory.

array([1, 2, 3], dtype=int32)

**3.Array operations**

In [24]:
np.max(x) #np.min, np.mean, np.median, np.std, np.exp, np.log....

np.int64(20)

In [25]:
m=np.arange(1,21).reshape(4,5)
n=np.arange(20,40).reshape(4,5)

In [26]:
m+n

array([[21, 23, 25, 27, 29],
       [31, 33, 35, 37, 39],
       [41, 43, 45, 47, 49],
       [51, 53, 55, 57, 59]])

In [27]:
m=np.arange(1,21).reshape(4,5)
n=np.arange(20,40).reshape(5,4)
np.dot(m,n)  #if both the arrays are 1d then it does dot product if any other d it performs matrix multiplication

array([[ 460,  475,  490,  505],
       [1160, 1200, 1240, 1280],
       [1860, 1925, 1990, 2055],
       [2560, 2650, 2740, 2830]])

**4.Indexing n Slicing**

In [28]:
a2=np.arange(12).reshape(3,4)

In [29]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [31]:
a2[0,:] #0th row all columns

array([0, 1, 2, 3])

In [32]:
a2[2,1:3] #2nd row 1,2 columns

array([ 9, 10])

In [33]:
a2[1:,1:]

array([[ 5,  6,  7],
       [ 9, 10, 11]])

In [34]:
a3=np.arange(27).reshape(3,3,3) #first index-> which 2d array, second index-> row, third index-> column

In [35]:
a3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [36]:
a3[1]

array([[ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17]])

In [37]:
a3[2,1:,1:]

array([[22, 23],
       [25, 26]])

**5.Iteration of nd arrays**

In [38]:
b1=np.arange(10)
for i in b1:
  print(i)

0
1
2
3
4
5
6
7
8
9


In [39]:
a3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [41]:
for i in a3:
  print(i)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[ 9 10 11]
 [12 13 14]
 [15 16 17]]
[[18 19 20]
 [21 22 23]
 [24 25 26]]


In [42]:
for i in np.nditer(a3): #converts any d to 1d
  print(i)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26


In [43]:
np.transpose(x)

array([[ 1,  5,  9, 13, 17],
       [ 2,  6, 10, 14, 18],
       [ 3,  7, 11, 15, 19],
       [ 4,  8, 12, 16, 20]])

In [44]:
x.T

array([[ 1,  5,  9, 13, 17],
       [ 2,  6, 10, 14, 18],
       [ 3,  7, 11, 15, 19],
       [ 4,  8, 12, 16, 20]])

In [46]:
# when a result is seen-> temporary change
#when a result is not seen -> permanent change

In [47]:
x.ravel() #converts any d to 1d

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

**6.Stacking and Splitting**

In [48]:
#to stack we shld have arrays of same shape
#use case = when we are fetching data from multiple sources and we wish to stack them together and analyze

In [49]:
n1=np.arange(1,10).reshape(3,3)

In [50]:
n1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [51]:
n2=np.arange(21,30).reshape(3,3)

In [52]:
n2

array([[21, 22, 23],
       [24, 25, 26],
       [27, 28, 29]])

In [54]:
np.hstack((n1,n2))

array([[ 1,  2,  3, 21, 22, 23],
       [ 4,  5,  6, 24, 25, 26],
       [ 7,  8,  9, 27, 28, 29]])

In [55]:
np.vstack((n1,n2))

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [21, 22, 23],
       [24, 25, 26],
       [27, 28, 29]])

In [56]:
np.hsplit(n1,3)

[array([[1],
        [4],
        [7]]),
 array([[2],
        [5],
        [8]]),
 array([[3],
        [6],
        [9]])]

In [57]:
np.vsplit(n1,3)

[array([[1, 2, 3]]), array([[4, 5, 6]]), array([[7, 8, 9]])]

**7.Fancy Indexing**

In [58]:
a2 #fancy indexing is when we cannot form patterns and we try to get specific elemnts only! then we go with a list

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [61]:
a2[[0,2],[1,3]]  #it takes like row 0 col 1 then row 2 column 3

array([ 1, 11])

In [62]:
a2[:,[0,3]]

array([[ 0,  3],
       [ 4,  7],
       [ 8, 11]])

In [64]:
a2[[0,2],:]

array([[ 0,  1,  2,  3],
       [ 8,  9, 10, 11]])

In [65]:
#boolean indexing

In [66]:
a2[a2%2==0]

array([ 0,  2,  4,  6,  8, 10])

In [67]:
a2[a2==8]

array([8])

In [70]:
a2[(a2-2==4) | (a2-2==8)]

array([ 6, 10])

**Broadcasting**

In [71]:
x1=np.arange(12).reshape(4,3)

In [72]:
x3=np.arange(3)

In [73]:
x1+x3

array([[ 0,  2,  4],
       [ 3,  5,  7],
       [ 6,  8, 10],
       [ 9, 11, 13]])

In [74]:
#ravel= faster operation it makes changes inplace as it shares same memory and reflects changes to original array
#flatten= slower operation it allocates new memory location changes made does not affect original array

In [75]:
# np.nan  indicates a missing value float datatype

In [79]:
r=np.array([1,2,3,np.nan,5])

In [81]:
r[~np.isnan(r)] #isnan is a boolean function that returns true if np.nan is present

array([1., 2., 3., 5.])